name: TheAcquaintances
favicon: null
layout_spectrum: 0.008971669245511293
typography_spectrum: 0.8399978042580187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9e9f13'
    - '#feffa9'
    - '#6c6366'
    - '#b82b00'
  brandStrength: 0.5
  lightness: 0.7807848553638905
  saturation: 0.559546162141487
  rhythmicContrast: 0.49131792155094445
purpose: []
